### ISSUE TITLE
ValueError in algorithm.py#round_order

### ISSUE THREAD

**Issue by alphaville76** [alphaville76/sharadar_db_bundle#10]
[2020-10-16 16:23:23.875714] INFO: Live Trading: Extended lifetime of asset WORK to 2030-10-16 00:00:00+00:00
Traceback (most recent call last):
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 172, in <module>
    run_live()
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 165, in run_live
    broker=IBBroker('localhost:4002:10'),
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/util/run_algo.py", line 490, in run_algorithm
    realtime_bar_target=realtime_bar_target
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/util/run_algo.py", line 261, in _run
    perf = algo.run()
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/live/algorithm_live.py", line 292, in run
    daily_stats = super(self.__class__, self).run(*args, **kwargs)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/algorithm.py", line 643, in run
    for perf in self.get_generator():
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/gens/tradesimulation.py", line 205, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/gens/tradesimulation.py", line 133, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/utils/events.py", line 218, in handle_data
    dt,
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/utils/events.py", line 237, in handle_data
    self.callback(context, data)
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 124, in rebalance
    order_target_percent(asset, one_third)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/utils/api_support.py", line 56, in wrapped
    return getattr(algo_instance, f.__name__)(*args, **kwargs)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/utils/api_support.py", line 125, in wrapped_method
    return method(self, *args, **kwargs)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/algorithm.py", line 1885, in order_target_percent
    style=style)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/utils/api_support.py", line 125, in wrapped_method
    return method(self, *args, **kwargs)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/algorithm.py", line 1275, in order
    limit_price, stop_price, style)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/algorithm.py", line 1280, in _calculate_order
    amount = self.round_order(amount)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/algorithm.py", line 1307, in round_order
    return int(round_if_near_integer(amount))
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/utils/math_utils.py", line 79, in round_if_near_integer
    if abs(a - round(a)) <= epsilon:
ValueError: cannot convert float NaN to integer

**Comment by alphaville76** [comment]
in case of NaN return 0
