### ISSUE TITLE
Error creating universe

### ISSUE THREAD

**Issue by alphaville76** [alphaville76/sharadar_db_bundle#5]
[2020-07-09 12:00:32.114006] INFO: sharadar_db_bundle: Start creating universe 'tradable_stocks_us' from 1997-12-31 00:00:00+00:00 to 2020-07-07 00:00:00+00:00 ...
[2020-07-09 12:00:32.117558] INFO: sharadar_db_bundle: Computing pipeline from 1997-12-31 00:00:00+00:00 to 2020-07-07 00:00:00+00:00...
[2020-07-09 12:00:32.118360] INFO: sharadar_db_bundle: Compute pipeline values in chunks of 120 days.
[2020-07-09 12:00:32.124120] INFO: sharadar_db_bundle: Compute values for pipeline from 1997-12-31 to 1998-06-23.
[2020-07-09 12:00:32.125489] WARNING: sharadar_db_bundle: Starting computing universe from 1998-10-16 instead of 1997-12-31 because of insufficient data.
[2020-07-09 12:00:32.129837] ERROR: sharadar_db_bundle: Traceback (most recent call last):
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/pipeline/engine.py", line 71, in _run_pipeline
    return super().run_pipeline(pipeline, start_date, end_date)
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline_live-1.3.0.5.0-py3.6-linux-x86_64.egg/zipline/pipeline/engine.py", line 297, in run_pipeline
    root_mask = self._compute_root_mask(start_date, end_date, extra_rows)
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/pipeline/engine.py", line 205, in _compute_root_mask
    lookback_length=extra_rows,
zipline.errors.NoFurtherDataError: 
Insufficient data to compute Pipeline:

lookback window started at 1997-12-31 00:00:00+00:00
earliest known date was 1997-12-31 00:00:00+00:00
199 extra rows of data were required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/loaders/ingest.py", line 181, in ingest
    _ingest(calendar, start_session, end_session)
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/loaders/ingest.py", line 281, in _ingest
    create_tradable_stocks_universe(output_dir, prices_start, prices_end)
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/pipeline/universes.py", line 97, in create_tradable_stocks_universe
    UniverseWriter(universes_dbpath).write(universe_name, screen, universe_start, universe_end)
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/pipeline/universes.py", line 37, in write
    stocks = self._execute_pipeline(screen, pipe_end, pipe_start)
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/pipeline/universes.py", line 56, in _execute_pipeline
    stocks = self.engine.run_pipeline(pipe, pipe_start, pipe_end, chunksize=120)
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/pipeline/engine.py", line 54, in run_pipeline
    chunks.append(self._run_pipeline(pipeline, s, e))
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/pipeline/engine.py", line 75, in _run_pipeline
    return self.run_pipeline(pipeline, new_start_date, end_date)
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle-1.0-py3.6.egg/sharadar/pipeline/engine.py", line 45, in run_pipeline
    chunksize,
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline_live-1.3.0.5.0-py3.6-linux-x86_64.egg/zipline/utils/date_utils.py", line 32, in compute_date_range_chunks
    start_date.strftime("%Y-%m-%d")))
ValueError: End date 1998-06-23 cannot precede start date 1998-10-16.

**Comment by alphaville76** [comment]
The first allowed data is **1998-10-16** and not **1997-12-31** because of the window_length=200 in AverageDollarVolume of TradableStocksUS

**Comment by alphaville76** [comment]
you can recreate the universe running the main in universe.py with a correct data range
