### ISSUE TITLE
could give install instruction like install.sh  on windows?

### ISSUE THREAD

**Issue by quant2008** [alphaville76/sharadar_db_bundle#53]
This package is great. But install.sh is for linux.
could you give install instruction on windows?
Thanks.

**Comment by quant2008** [comment]
I installed sharadar_db_bundle on windows 10 with zipline-reloaded. I have a free NASDAQ_API_KEY. and I set NASDAQ_API_KEY="my freeAPI key".
Then after installation. I execute sharadar-zipline ingest in my vscode terminal, hoping to download free sample data from Sharadar, but came accross the following error. could you point me a direction?
Thanks.

Traceback (most recent call last):
  File "E:\anaconda3\envs\zip38\Scripts\sharadar-zipline-script.py", line 33, in <module>
    sys.exit(load_entry_point('sharadar-db-bundle==2.0', 'console_scripts', 'sharadar-zipline')())
  File "E:\anaconda3\envs\zip38\Scripts\sharadar-zipline-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "E:\anaconda3\envs\zip38\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "E:\anaconda3\envs\zip38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\__main__.py", line 23, in <module>
    from sharadar.util.run_algo import _run, load_extensions
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\util\run_algo.py", line 10, in <module>      
    from sharadar.pipeline.engine import *
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\pipeline\engine.py", line 9, in <module>     
    from sharadar.data.sql_lite_assets import SQLiteAssetFinder
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\data\sql_lite_assets.py", line 8, in <module>
    from sharadar.util.logger import log
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\util\logger.py", line 43, in <module>        
    log = SharadarDbBundleLogger()
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\util\logger.py", line 22, in __init__
    self.filename = os.path.join(env["HOME"], "log",
  File "E:\anaconda3\envs\zip38\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by quant2008** [comment]
I have managed to solve this. just set HOME env variable.
