### ISSUE TITLE
 Parameter `end` received with timezone defined as 'UTC' although a Date must be timezone naive.

### ISSUE THREAD

**Issue by quant2008** [alphaville76/sharadar_db_bundle#55]
Hello, I use zipline-reloaded. and when executing sharadar-zipline ingest, I got the following error.
Any idea?

(zip38) E:\myquant\sharadar_db_bundle-master>sharadar-zipline ingest
logfiles: C:\Users\Administrator\.zipline\log\sharadar-zipline_2023-03-12_2205.log
[2023-03-12 22:05:29] INFO: Start ingesting SEP, SFP and SF1 data into C:\Users\Administrator\.zipline\data\sharadar\latest ...
[2023-03-12 22:05:30] ERROR: Traceback (most recent call last):
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\loaders\ingest_sharadar.py", line 350, in ingest
    _ingest(start_date, calendar)
...
[2023-03-12 22:19:21] ERROR: Traceback (most recent call last):
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\loaders\ingest_sharadar.py", line 351, in ingest
    _ingest(start_date, calendar)
  File "E:\anaconda3\envs\zip38\lib\site-packages\sharadar_db_bundle-2.0-py3.8.egg\sharadar\loaders\ingest_sharadar.py", line 165, in _ingest
    sessions = calendar.sessions_in_range(start_session, end_session)
  File "E:\anaconda3\envs\zip38\lib\site-packages\exchange_calendars\exchange_calendar.py", line 2199, in sessions_in_range
    slc = self._get_sessions_slice(start, end, _parse)
  File "E:\anaconda3\envs\zip38\lib\site-packages\exchange_calendars\exchange_calendar.py", line 2176, in _get_sessions_slice
    start, end = self._parse_start_end_dates(start, end, _parse)
  File "E:\anaconda3\envs\zip38\lib\site-packages\exchange_calendars\exchange_calendar.py", line 2172, in _parse_start_end_dates
    return parse_date(start, "start", self), parse_date(end, "end", self)
  File "E:\anaconda3\envs\zip38\lib\site-packages\exchange_calendars\calendar_helpers.py", line 379, in parse_date
    raise ValueError(
ValueError: Parameter `end` received with timezone defined as 'UTC' although a Date must be timezone naive.

**Comment by alphaville76** [comment]
I'm using now the last version of zipline-reloaded and switch to timezone navice datetimes
