### ISSUE TITLE
sqlite3.OperationalError: database is locked 

### ISSUE THREAD

**Issue by ruidacn** [alphaville76/sharadar_db_bundle#59]
[2024-09-10 18:36:57] ERROR: Traceback (most recent call last):
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sharadar/loaders/ingest_sharadar.py", line 395, in ingest
    _ingest(start_date, calendar)
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sharadar/loaders/ingest_sharadar.py", line 232, in _ingest
    asset_db_writer.write(equities=equities_df, exchanges=EXCHANGE_DF)
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/zipline/assets/asset_writer.py", line 814, in write
    self._real_write(
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/zipline/assets/asset_writer.py", line 493, in _real_write
    self._write_df_to_table(
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sharadar/data/sql_lite_assets.py", line 317, in _write_df_to_table
    conn.execute(text(cmd), params)
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/anaconda3/envs/sharadar_db_bundle/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT OR REPLACE INTO "exchanges" ("exchange","country_code","canonical_name") VALUES (?,?,?)]
[parameters: ('NYSE', 'US', 'NYSE')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

A file "assets-7.sqlite" was created. I has table created but no data entry. I'v tried to set sqlite's connection timeout to 20s. It didn't solve the problem.

**Comment by ruidacn** [comment]
I have solved it by adding "txn.commit()" at the end in SQLiteAssetDBWriter's _init_db method
