### ISSUE TITLE
IB Broker: !!!WARNING: I did not manage to subscribe to NAV-PD 

### ISSUE THREAD

**Issue by alphaville76** [alphaville76/sharadar_db_bundle#8]
[2020-08-27 18:56:03.697191] INFO: IB Broker: Subscribing to market data for Equity(113764 [NAV-PD])
[2020-08-27 18:56:03.761880] ERROR: IB Broker: [200] No security definition has been found for the request (0)
[2020-08-27 18:56:24.732727] WARNING: IB Broker: !!!WARNING: I did not manage to subscribe to NAV-PD 
Traceback (most recent call last):
  File "/home/XYZ/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 194, in <module>
    run_live()
  File "/home/XYZ/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 187, in run_live
    broker=IBBroker('localhost:4002:1'),
  File "/home/XYZ/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/util/run_algo.py", line 495, in run_algorithm
    execution_id=execution_id
  File "/home/XYZ/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/util/run_algo.py", line 246, in _run
    perf = algo.run()
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/algorithm_live.py", line 274, in run
    daily_stats = super(self.__class__, self).run(*args, **kwargs)
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/algorithm.py", line 668, in run
    for perf in self.get_generator():
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/gens/tradesimulation.py", line 205, in transform
    for capital_change_packet in every_bar(dt):
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/gens/tradesimulation.py", line 133, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/utils/events.py", line 218, in handle_data
    dt,
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/utils/events.py", line 237, in handle_data
    self.callback(context, data)
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/algorithm_live.py", line 106, in handle_data
    super(self.__class__, self).handle_data(data)
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/algorithm.py", line 474, in handle_data
    self._handle_data(self, data)
  File "/home/XYZ/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 64, in handle_data
    rebalance(context, data)
  File "/home/XYZ/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 144, in rebalance
    print("can_trade: " + str(data.can_trade(long)))
  File "zipline/_protocol.pyx", line 121, in zipline._protocol.check_parameters.__call__.assert_keywords_and_call
  File "zipline/_protocol.pyx", line 492, in zipline._protocol.BarData.can_trade
  File "zipline/_protocol.pyx", line 534, in zipline._protocol.BarData._can_trade_for_asset
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/data/data_portal_live.py", line 30, in get_spot_value
    return self.broker.get_spot_value(assets, field, dt, data_frequency)
  File "/home/XYZ/zipline/lib64/python3.6/site-packages/zipline_trader-1.3.0+638.gcbf6e602-py3.6-linux-x86_64.egg/zipline/gens/brokers/ib_broker.py", line 969, in get_spot_value
    bars = self._tws.bars[symbol]
KeyError: 'NAV-PD'

**Comment by alphaville76** [comment]
Same for  LGF.B

**Comment by alphaville76** [comment]
NAV-PD -> NAV
P – First class preferred shares
D – New issue of existing stock
https://www.investopedia.com/terms/s/stocksymbol.asp

**Comment by alphaville76** [comment]
IB Lookup Tool
https://misc.interactivebrokers.com/cstools/contract_info/v3.10/index.php

**Comment by alphaville76** [comment]
LGF.B -> LGF B
https://misc.interactivebrokers.com/cstools/contract_info/v3.10/index.php?action=Conid Info&wlId=IB&conid=257460317&lang=en&ib_entity=
