### ISSUE TITLE
KeyError in self._tws.bars[symbol]['last_trade_price']

### ISSUE THREAD

**Issue by alphaville76** [alphaville76/sharadar_db_bundle#9]
[2020-10-16 16:28:56.629492] INFO: IB Broker: Subscribing to market data for Equity(110316 [BILL])
[2020-10-16 16:29:13.909743] INFO: IB Broker: Order-135 executed @ 2020-10-16 18:29:13: MYRG current: 100 @ $45.35 total: 3400 @ $45.346176 exec_id: 0000e0d5.5fa6bedb.01.01 by client-10
[2020-10-16 16:29:15.913442] INFO: IB Broker: Order-135 executed @ 2020-10-16 18:29:15: MYRG current: 100 @ $45.35 total: 3500 @ $45.346286 exec_id: 0000e0d5.5fa6bedd.01.01 by client-10
[2020-10-16 16:29:15.955901] INFO: IB Broker: Order-135 executed @ 2020-10-16 18:29:15: MYRG current: 100 @ $45.35 total: 3600 @ $45.346389 exec_id: 0000e0d5.5fa6bede.01.01 by client-10
[2020-10-16 16:29:43.964081] INFO: IB Broker: Order-135 executed @ 2020-10-16 18:29:43: MYRG current: 98 @ $45.35 total: 3698 @ $45.346485 exec_id: 0000e0d5.5fa6bf12.01.01 by client-10
Traceback (most recent call last):
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 172, in <module>
    run_live()
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 165, in run_live
    broker=IBBroker('localhost:4002:10'),
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/util/run_algo.py", line 490, in run_algorithm
    realtime_bar_target=realtime_bar_target
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/util/run_algo.py", line 261, in _run
    perf = algo.run()
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/live/algorithm_live.py", line 292, in run
    daily_stats = super(self.__class__, self).run(*args, **kwargs)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/algorithm.py", line 643, in run
    for perf in self.get_generator():
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/gens/tradesimulation.py", line 228, in transform
    metrics_tracker,
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/gens/tradesimulation.py", line 302, in _get_minute_message
    self.data_portal,
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/finance/metrics/tracker.py", line 217, in handle_minute_close
    self.sync_last_sale_prices(dt, data_portal)
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/finance/metrics/tracker.py", line 201, in sync_last_sale_prices
    handle_non_market_minutes=handle_non_market_minutes,
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/finance/ledger.py", line 464, in sync_last_sale_prices
    handle_non_market_minutes=handle_non_market_minutes,
  File "/home/xyz/zipline/lib64/python3.6/site-packages/zipline/finance/ledger.py", line 285, in sync_last_sale_prices
    update_position_last_sale_prices(self.positions, get_price, dt)
  File "zipline/finance/_finance_ext.pyx", line 14, in zipline.finance._finance_ext.update_position_last_sale_prices
  File "zipline/finance/_finance_ext.pyx", line 32, in zipline.finance._finance_ext.update_position_last_sale_prices
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/live/data_portal_live.py", line 122, in get_scalar_asset_spot_value
    prices = self.broker.get_realtime_bars([asset], data_frequency)
  File "/home/xyz/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/live/brokers/ib_broker.py", line 1021, in get_realtime_bars
    trade_prices = self._tws.bars[symbol]['last_trade_price']
KeyError: 'BILL'
[2020-10-16 16:30:47.679114] WARNING: IB Broker: !!!WARNING: I did not manage to subscribe to BILL

**Comment by alphaville76** [comment]
[2020-10-26 18:51:31.969936] INFO: IB Broker: Subscribing to market data for Equity(124789 [NGVT])
Traceback (most recent call last):
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 173, in <module>
    run_live()
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle/algo/live/rsi.py", line 166, in run_live
    broker=IBBroker('localhost:4002:10'),
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/util/run_algo.py", line 491, in run_algorithm
    realtime_bar_target=realtime_bar_target
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/util/run_algo.py", line 261, in _run
    perf = algo.run()
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/live/algorithm_live.py", line 293, in run
    daily_stats = super(self.__class__, self).run(*args, **kwargs)
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline/algorithm.py", line 643, in run
    for perf in self.get_generator():
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline/gens/tradesimulation.py", line 228, in transform
    metrics_tracker,
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline/gens/tradesimulation.py", line 302, in _get_minute_message
    self.data_portal,
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline/finance/metrics/tracker.py", line 217, in handle_minute_close
    self.sync_last_sale_prices(dt, data_portal)
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline/finance/metrics/tracker.py", line 201, in sync_last_sale_prices
    handle_non_market_minutes=handle_non_market_minutes,
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline/finance/ledger.py", line 464, in sync_last_sale_prices
    handle_non_market_minutes=handle_non_market_minutes,
  File "/home/costantino/zipline/lib64/python3.6/site-packages/zipline/finance/ledger.py", line 285, in sync_last_sale_prices
    update_position_last_sale_prices(self.positions, get_price, dt)
  File "zipline/finance/_finance_ext.pyx", line 14, in zipline.finance._finance_ext.update_position_last_sale_prices
  File "zipline/finance/_finance_ext.pyx", line 32, in zipline.finance._finance_ext.update_position_last_sale_prices
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/live/data_portal_live.py", line 122, in get_scalar_asset_spot_value
    prices = self.broker.get_realtime_bars([asset], data_frequency)
  File "/home/costantino/zipline/lib/python3.6/site-packages/sharadar_db_bundle/sharadar/live/brokers/ib_broker.py", line 1015, in get_realtime_bars
    trade_prices = self._tws.bars[symbol]['last_trade_price']
KeyError: 'NGVT'
[2020-10-26 18:53:23.061594] WARNING: IB Broker: !!!WARNING: I did not manage to subscribe to NGVT
